=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 4/gestoria.dtd
<!ELEMENT Gestoria (Sede+) >
<!ELEMENT Sede (Empleado, Fecha, Cliente*) >
<!ELEMENT Empleado (#PCDATA) >
<!ELEMENT Fecha (#PCDATA) >
<!ELEMENT Cliente (codCliente, descCliente, vivienda, coste, resumen, plazo) >
<!ELEMENT codCliente (#PCDATA) >
<!ELEMENT descCliente (#PCDATA) >
<!ELEMENT vivienda (#PCDATA) >
<!ELEMENT coste (#PCDATA) >
<!ELEMENT resumen (#PCDATA) >
<!ELEMENT plazo (#PCDATA) >

=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 4/gestoria.xml
<!DOCTYPE Gestoria SYSTEM "gestoria.dtd">
<Gestoria>
    <Sede>
       <Empleado>Juan Perez</Empleado>
       <Fecha>2024-01-22</Fecha>
       <Cliente>
         <codCliente>AAA-112</codCliente>
         <descCliente>Insolvente</descCliente>
         <vivienda>10</vivienda>
         <coste>100</coste>
         <resumen>Producto muy frágil</resumen>
         <plazo>10</plazo>
       </Cliente>
       <Cliente>
         <codCliente>BBB-113</codCliente>
         <descCliente>Insolvente</descCliente>
         <vivienda>10</vivienda>
         <coste>100</coste>
         <resumen>Producto no frágil</resumen>
         <plazo>17</plazo>
       </Cliente>
    </Sede>
   </Gestoria>
