=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 6/modulos.dtd
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (nombre, contenidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contenidos (ud+)>
<!ELEMENT ud (descripcion)>
<!ATTLIST ud tipo CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>

=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 6/modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modulos SYSTEM "modulos.dtd">
<modulos>
    <modulo>
        <nombre>Programación</nombre>
        <contenidos>
            <ud tipo="Teórica">
                <descripcion>Introducción a la Programación</descripcion>
            </ud>
            <ud tipo="Práctica">
                <descripcion>Programación Orientada a Objetos</descripcion>
            </ud>
        </contenidos>
    </modulo>
    <modulo>
        <nombre>Base de Datos</nombre>
        <contenidos>
            <ud tipo="Teórica">
                <descripcion>Modelos de Datos</descripcion>
            </ud>
            <ud tipo="Práctica">
                <descripcion>SQL Avanzado</descripcion>
            </ud>
        </contenidos>
    </modulo>
</modulos>
