<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (autores, titulo, editorial, fecha_Publicacion, ISBN)>
    <!ELEMENT autores (autor+)>
    <!ELEMENT autor (apellido1, apellido2, nombre)>
    <!ELEMENT apellido1 (#PCDATA)>
    <!ELEMENT apellido2 (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT fecha_Publicacion (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
]>

<biblioteca>
    <libro>
        <autores>
            <autor>
                <apellido1>Brown</apellido1>
                <apellido2></apellido2>
                <nombre>Dan</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>El Código Da Vinci</titulo>
        <editorial>Planeta</editorial>
        <fecha_Publicacion>29/08/2017</fecha_Publicacion>
        <ISBN>978-8408175728</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Ónegas</apellido1>
                <apellido2></apellido2>
                <nombre>Sonsoles</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Las Hijas de la Criada</titulo>
        <editorial>Planeta</editorial>
        <fecha_Publicacion>08/11/2023</fecha_Publicacion>
        <ISBN>9788408280170</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>del Valle</apellido1>
                <apellido2>Inclán</apellido2>
                <nombre>Ramón</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Luces de Bohemia. Esperpento</titulo>
        <editorial>Colección Austral</editorial>
        <fecha_Publicacion>31/07/1920</fecha_Publicacion>
        <ISBN>8423995879</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>García</apellido1>
                <apellido2>Marquez</apellido2>
                <nombre>Gabriel</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Cien Años de Soledad</titulo>
        <editorial>Edhasa</editorial>
        <fecha_Publicacion>5/06/1967</fecha_Publicacion>
        <ISBN>9580600023</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Bradbury</apellido1>
                <apellido2></apellido2>
                <nombre>Ray</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Ray Bradbury: Fahrenheit 451</titulo>
        <editorial>Minotauro</editorial>
        <fecha_Publicacion>01/03/2020</fecha_Publicacion>
        <ISBN>978-950-547-212-3</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Henri</apellido1>
                <apellido2>Beyle</apellido2>
                <nombre>Stendhal</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Rojo y Negro</titulo>
        <editorial>Austral</editorial>
        <fecha_Publicacion>1830</fecha_Publicacion>
        <ISBN>9786070763427</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Camus</apellido1>
                <apellido2></apellido2>
                <nombre>Albert</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>El Extranjero</titulo>
        <editorial>Alianza</editorial>
        <fecha_Publicacion>1942</fecha_Publicacion>
        <ISBN>978-8420669786</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Miller</apellido1>
                <apellido2></apellido2>
                <nombre>Henry</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Trópico de Cáncer</titulo>
        <editorial>Edhasa</editorial>
        <fecha_Publicacion>1934</fecha_Publicacion>
        <ISBN>9788437607382</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Orwell</apellido1>
                <apellido2></apellido2>
                <nombre>George</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>1984</titulo>
        <editorial>Debolsillo</editorial>
        <fecha_Publicacion>8/05/1949</fecha_Publicacion>
        <ISBN>9789588773834</ISBN>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Graves</apellido1>
                <apellido2></apellido2>
                <nombre>Robert</nombre>
            </autor>
            <autor>
                <apellido1></apellido1>
                <apellido2></apellido2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Yo Claudio</titulo>
        <editorial>Alianza</editorial>
        <fecha_Publicacion>1935</fecha_Publicacion>
        <ISBN>9788420689852</ISBN>
    </libro>
</biblioteca>