=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 4/Actividad 4/gestionClientes.dtd
<!ELEMENT gestionClientes (sede)>
<!ELEMENT sede (codigoSede,empleado,fechaAlta,direccion,cliente)>
<!ELEMENT codigoSede (#PCDATA)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT cliente (codigoCliente,descripcion,numViviendas,costeVivienda,resumenViviendas,plazoHacienda)>
<!ELEMENT codigoCliente (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numViviendas (#PCDATA)>
<!ELEMENT costeVivienda (#PCDATA)>
<!ELEMENT resumenViviendas (#PCDATA)>
<!ELEMENT plazoHacienda (#PCDATA)>

=== agarper2311/Lenguaje-De-Marcas/Unidad-4/Actividad 4/gestionClientes.xml
<!DOCTYPE gestionClientes SYSTEM "Actividad 4\gestionClientes.dtd">
<gestionClientes>
  <sede>
    <codigoSede>S01A3456</codigoSede>
    <empleado>Juan Perez</empleado>
    <fechaAlta>2024-01-18</fechaAlta>
    <direccion>Calle Principal, 123</direccion>
    <cliente>
      <codigoCliente>ABC-123</codigoCliente>
      <descripcion>solvente</descripcion>
      <numViviendas>3</numViviendas>
      <costeVivienda>150000.00</costeVivienda>
      <resumenViviendas>Resumen de las viviendas</resumenViviendas>
      <plazoHacienda>2024-12-31</plazoHacienda>
    </cliente>
  </sede>
</gestionClientes>
